objects/Account/fields/PrimaryContactId__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the primary person to contact for anything related to this account.</description>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order/fields/Associated_Contact__c.field-meta.xml
<CustomField>
    <fullName>Associated_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associate a contact to the order by default during order creation (if any). The contact has to be the primary contact on the account</description>
    <label>Associated Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/OrderTriggerHandler.cls
/**
* @author          Maumita
* @date            Jul 03, 2023
* @description     Trigger Handler class for Order Object to associate a Primary contact to the order 
* 
* */

public class OrderTriggerHandler {
    public static void beforeInsetOrder(List<Order> newOrder){
        List<Account> primCntList; 
        Id accId;
        Id contactId;
        for(Order ord: newOrder){
            System.debug('trigger handler class newOrder');
            if(ord.AccountId != null){
                accId = ord.AccountId;
                primCntList = [SELECT PrimaryContactId__c 
                               FROM Account 
                               WHERE Id= :accId
                               AND PrimaryContactId__c!= null
                               LIMIT 1];
                
                if (primCntList.size() > 0){
                    contactId=primCntList[0].PrimaryContactId__c;
                    ord.Associated_Contact__c = contactId;
                    System.debug('Associated_Contact__c updated '+contactId);
                }
            }
        }
    }
    
}